// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NASA_API_Endpoint.DBModels;

#nullable disable

namespace NASAAPIEndpoint.Migrations
{
    [DbContext(typeof(AsteroidDBContext))]
    [Migration("20240123171640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NASA_API_Endpoint.Models.AsteroidModel", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Diametro")
                        .HasColumnType("float");

                    b.Property<string>("Fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Velocidad")
                        .HasColumnType("float");

                    b.HasKey("Nombre");

                    b.ToTable("Asteroid");
                });
#pragma warning restore 612, 618
        }
    }
}
